# Generated by Django 3.2.9 on 2022-02-13 06:11

import auction_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0016_item_evaluation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftuser',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='production_year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1400), auction_app.models.max_value_current_year]),
        ),
    ]
